title: Enterprise Architecture Patterns
description: Your go-to resource for all architectural guidance, decisions, and onboarding materials across the OS² open source landscape.
logo: "assets/images/os2_logo.png"
footer_content: " "

aux_links:
  "OS² offentligt digitaliseringsfællesskab": "https://os2.eu"

theme: just-the-docs

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.9.0"

callouts:
  default:
    color: green